id: AE42A1BEE
title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
type: translation
pechas:
- I65A6466C
- I22B11B84
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:57:20.142491
  last_modified_at: 2023-01-04 11:57:20.142504
  collections:
  - Gönpo Tseten Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I65A6466C/0F13: '3181'
  I22B11B84/D4B7: '3181'
